---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Network definition to connect Fedora VMs
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: fedora-external
  namespace: ocp-virt-pgd
spec:
  config: '{
    "name":"fedora-external",
    "type":"cnv-bridge",
    "cniVersion":"0.3.1",
    "bridge":"br1",
    "macspoofchk":true,
    "ipam":{}
    }'