---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: fedora-04
  labels:
    template.kubevirt.io/type: vm
    os.template.kubevirt.io/fedora36: 'true'
    workload.template.kubevirt.io/server: 'true'
  annotations:
    name.os.template.kubevirt.io/fedora36: Fedora 36
    description: Template to deploy a basic Fedora connected to the Pod Network with an extra empty disk. 
    openshift.io/display-name: Fedora VM 03
    openshift.io/documentation-url: https://github.com/alvarolop/ocp-virtualization-playground
    template.kubevirt.io/provider: Alvaro
    iconClass: icon-fedora
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      name: ${VM_NAME}
      namespace: ${VM_NAMESPACE}
      annotations:
        description: "VM ${VM_NAME}"
      labels:
        app: ${VM_NAME}
        os.template.kubevirt.io/fedora36: 'true'
    spec:
      running: true
      template:
        metadata:
          annotations:
            vm.kubevirt.io/flavor: small
            vm.kubevirt.io/os: fedora36
            vm.kubevirt.io/workload: server
          labels:
            kubevirt.io/domain: ${VM_NAME}
            kubevirt.io/size: small
            app: ${VM_NAME}
        spec:
          domain:
            cpu:
              cores: 2
              sockets: 1
              threads: 1
            devices:
              disks:
                - bootOrder: 1
                  disk:
                    bus: virtio
                  name: rootdisk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
                - disk:
                    bus: virtio
                  serial: SHAREDFS
                  name: sharedfs
                  shareable: true
              # filesystems:
              #   - name: sharedfs
              #     virtiofs: {}
              interfaces:
                - masquerade: {}
                  model: virtio
                  name: default
              networkInterfaceMultiqueue: true
              rng: {}
            features:
              acpi: {}
              smm:
                enabled: true
            firmware:
              bootloader:
                efi: {}
            machine:
              type: q35
            resources:
              requests:
                memory: 2Gi
          hostname: ${VM_NAME}
          networks:
            - name: default
              pod: {}
          terminationGracePeriodSeconds: 180
          volumes:
            - name: rootdisk
              containerDisk:
                image: 'quay.io/containerdisks/fedora:36'
            - name: sharedfs
              persistentVolumeClaim:
                claimName: ${SHARED_FS}
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  ssh_authorized_keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA66H7xHgj94dzEmhW4ngURgd+nIldwiHzCqKrFSH22jG+YiFqRZtgIO1MzapYWbH7GE1xqW3W4p0e/Tk2WrbQR4mjolgThRJjHPBsnT77h8vynzlj0lGIJEQdnhEUtKLgtDqbHyfbDJGYjET+kNKuZe58wRZ3h5zAbIbzOUoTxA13lp640TP1sBX4Il8SO7BWaIjtRsOcYnQZEjy8oZ0JWS7Q3eEKsC9sG7XA1RQrkC1e3fOqEDE2rYrNQ122s+RcTD0ymL2KFGnFmf9UsfFvyVTCQYyAFzTO5IVpM+SLlVzoZAPVgvlsm70MXb51fFmOTJEzvqJGLWKHcZHrPwlP alvaro@localhost.localdomain
                  ssh_pwauth: True
                  user: fedora
                  password: fedora
                  chpasswd:
                    expire: false
                  bootcmd:
                    # mount the extra filesystem
                    - "mkdir /mnt/extra"
                    - "mount /dev/$(lsblk --nodeps -no name,serial | grep SHAREDFS | cut -f1 -d' ') /mnt/extra"
              name: cloudinitdisk
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${VM_NAME}
        os.template.kubevirt.io/fedora36: 'true'
      name: ${VM_NAME}
      namespace: ${VM_NAMESPACE}
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: ${VM_NAME}
      type: ClusterIP
parameters:
  - name: VM_NAMESPACE
    description: "The namespace where the VM will be deployed."
    required: false
    value: vms-test
  - name: VM_NAME
    description: "The name of the VM deployment."
    required: false
    value: fedora-04
  - name: SHARED_FS
    description: "The PVC name."
    required: false
    value: shared-filesystem
