---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: shared-disk
objects:
  - apiVersion: cdi.kubevirt.io/v1alpha1
    kind: DataVolume
    metadata:
      name: ${PVC_NAME}
      namespace: ${VM_PROJECT}
      labels:
        app: ${PVC_NAME}
    spec:
      pvc:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 2Gi
        storageClassName: efs-csi
      source:
        blank: {}
parameters:
  - name: VM_PROJECT
    description: "The project where the VM will be deployed."
    required: false
    value: vms-test
  - name: PVC_NAME
    description: "The PVC name."
    required: false
    value: efs-shared-filesystem