---
apiVersion: template.openshift.io/v1
kind: Template
objects:
  - apiVersion: project.openshift.io/v1
    kind: Project
    metadata:
      name: ${VM_PROJECT}
      annotations:
        openshift.io/description: "Project to deploy different VM configurations"
        openshift.io/display-name: "VMs Test Environment"
parameters:
  - name: VM_PROJECT
    description: "The project where the VM will be deployed."
    required: false
    value: vms-test
