apiVersion: nmstate.io/v1beta1
kind: NodeNetworkState
metadata:
  name: metal-node
status:
  currentState:
    dns-resolver:
      config:
        search: null
        server: null
      running:
        search:
        - eu-west-3.compute.internal
        server:
        - 10.0.0.2
    interfaces:
    - accept-all-mac-addresses: false
      ethtool:
        feature:
          tx-generic-segmentation: true
          tx-tcp-segmentation: true
          tx-vlan-hw-insert: true
      ipv4:
        address: []
        enabled: false
      ipv6:
        address: []
        enabled: false
      mac-address: E6:42:94:26:FF:46
      mtu: 8951
      name: br0
      state: down
      type: ovs-interface
    - accept-all-mac-addresses: false
      ethtool:
        coalesce:
          adaptive-rx: false
          rx-usecs: 0
          tx-usecs: 64
        feature:
          rx-checksum: true
          rx-hashing: true
          tx-generic-segmentation: true
        ring:
          rx: 1024
          tx: 1024
      ipv4:
        address:
        - ip: 10.0.141.29
          prefix-length: 19
        auto-dns: true
        auto-gateway: true
        auto-route-table-id: 0
        auto-routes: true
        dhcp: true
        enabled: true
      ipv6:
        addr-gen-mode: stable-privacy
        address:
        - ip: fe80::4705:ff84:87c5:151e
          prefix-length: 64
        auto-dns: true
        auto-gateway: true
        auto-route-table-id: 0
        auto-routes: true
        autoconf: true
        dhcp: true
        enabled: true
      lldp:
        enabled: false
      mac-address: 06:08:8D:67:8D:14
      mtu: 9001
      name: ens1
      state: up
      type: ethernet
    - accept-all-mac-addresses: false
      ethernet:
        auto-negotiation: false
        duplex: full
        speed: 25000
      ethtool:
        coalesce:
          adaptive-rx: false
          rx-usecs: 0
          tx-usecs: 64
        feature:
          rx-checksum: true
          rx-hashing: true
          tx-generic-segmentation: true
        ring:
          rx: 1024
          tx: 1024
      ipv4:
        address:
        - ip: 10.0.146.212
          prefix-length: 19
        auto-dns: true
        auto-gateway: true
        auto-route-table-id: 0
        auto-routes: true
        dhcp: true
        enabled: true
      ipv6:
        addr-gen-mode: stable-privacy
        address:
        - ip: fe80::2dc:241c:505:29eb
          prefix-length: 64
        auto-dns: true
        auto-gateway: true
        auto-route-table-id: 0
        auto-routes: true
        autoconf: true
        dhcp: true
        enabled: true
      lldp:
        enabled: false
      mac-address: 06:27:3C:BD:BA:40
      mtu: 9001
      name: ens6
      state: up
      type: ethernet
    - accept-all-mac-addresses: false
      ethtool:
        feature:
          tx-generic-segmentation: true
          tx-tcp-segmentation: true
      ipv4:
        address:
        - ip: 127.0.0.1
          prefix-length: 8
        enabled: true
      ipv6:
        address:
        - ip: ::1
          prefix-length: 128
        enabled: true
      mac-address: "00:00:00:00:00:00"
      mtu: 65536
      name: lo
      state: up
      type: unknown
    - accept-all-mac-addresses: false
      ethtool:
        feature:
          tx-generic-segmentation: true
          tx-tcp-segmentation: true
          tx-vlan-hw-insert: true
      ipv4:
        address:
        - ip: 10.130.4.1
          prefix-length: 23
        enabled: true
      ipv6:
        address:
        - ip: fe80::44d:b5ff:fed3:3ce2
          prefix-length: 64
        enabled: true
      mac-address: 06:4D:B5:D3:3C:E2
      mtu: 8951
      name: tun0
      state: up
      type: ovs-interface
    - accept-all-mac-addresses: false
      ethtool:
        feature:
          rx-checksum: true
          tx-generic-segmentation: true
          tx-tcp-segmentation: true
      ipv4:
        address: []
        enabled: false
      ipv6:
        address:
        - ip: fe80::58a2:fbff:fec5:8a45
          prefix-length: 64
        enabled: true
      mac-address: 5A:A2:FB:C5:8A:45
      mtu: 65000
      name: vxlan_sys_4789
      state: up
      type: vxlan
      vxlan:
        base-iface: ""
        destination-port: 4789
        id: 0
        remote: ""
    routes:
      config:
      - destination: 10.128.0.0/14
        metric: 0
        next-hop-address: 0.0.0.0
        next-hop-interface: tun0
        table-id: 254
      - destination: 172.30.0.0/16
        metric: 0
        next-hop-address: 0.0.0.0
        next-hop-interface: tun0
        table-id: 254
      running:
      - destination: fe80::/64
        metric: 256
        next-hop-address: '::'
        next-hop-interface: vxlan_sys_4789
        table-id: 254
      - destination: fe80::/64
        metric: 256
        next-hop-address: '::'
        next-hop-interface: tun0
        table-id: 254
      - destination: fe80::/64
        metric: 1024
        next-hop-address: '::'
        next-hop-interface: ens6
        table-id: 254
      - destination: fe80::/64
        metric: 1024
        next-hop-address: '::'
        next-hop-interface: ens1
        table-id: 254
      - destination: 0.0.0.0/0
        metric: 100
        next-hop-address: 10.0.128.1
        next-hop-interface: ens6
        table-id: 254
      - destination: 0.0.0.0/0
        metric: 101
        next-hop-address: 10.0.128.1
        next-hop-interface: ens1
        table-id: 254
      - destination: 10.0.128.0/19
        metric: 100
        next-hop-address: 0.0.0.0
        next-hop-interface: ens6
        table-id: 254
      - destination: 10.0.128.0/19
        metric: 101
        next-hop-address: 0.0.0.0
        next-hop-interface: ens1
        table-id: 254
      - destination: 10.128.0.0/14
        metric: 0
        next-hop-address: 0.0.0.0
        next-hop-interface: tun0
        table-id: 254
      - destination: 172.30.0.0/16
        metric: 0
        next-hop-address: 0.0.0.0
        next-hop-interface: tun0
        table-id: 254
  handlerNetworkManagerVersion: 1.36.0-13.el8_6
  handlerNmstateVersion: 1.3.3
  hostNetworkManagerVersion: 1.36.0
  lastSuccessfulUpdateTime: "2023-04-17T08:14:38Z"