---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-policy
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
    usage: virtualization
  desiredState:
    interfaces:
    - name: br1
      description: Linux bridge with ens1 as a port
      type: linux-bridge
      state: up
      ipv4:
        dhcp: true
        enabled: true
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: ens1