---
apiVersion: template.openshift.io/v1
kind: Template
objects:
  - apiVersion: k8s.cni.cncf.io/v1
    kind: NetworkAttachmentDefinition
    metadata:
      annotations:
        description: Network definition to connect Fedora VMs
        # k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/fedora-external
      name: fedora-external
      namespace: ${VM_PROJECT}
    spec:
      config: '{
        "name":"fedora-external",
        "type":"cnv-bridge",
        "cniVersion":"0.3.1",
        "bridge":"br1",
        "macspoofchk":true,
        "ipam":{}
        }'
parameters:
  - name: VM_PROJECT
    description: "The project where the VM will be deployed."
    required: false
    value: vms-test
