apiVersion: template.openshift.io/v1
kind: Template
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${POD_NAME}
      namespace: ${NAMESPACE}
      labels:
        app: ${POD_NAME}
        app.kubernetes.io/component: ${POD_NAME}
        app.kubernetes.io/instance: ${POD_NAME}
        app.kubernetes.io/name: ${POD_NAME}
        app.kubernetes.io/part-of: ${POD_NAME}-app
        app.openshift.io/runtime: shadowman
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ${POD_NAME}
      template:
        metadata:
          labels:
            app: ${POD_NAME}
            deployment: ${POD_NAME}
        spec:
          containers:
            - name: ${POD_NAME}
              image: registry.redhat.io/rhel9/support-tools:9.5
              command:
                - "/bin/sleep"
                - "infinity"
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${POD_NAME}
      namespace: ${NAMESPACE}
      labels:
        app: ${POD_NAME}
        app.kubernetes.io/component: ${POD_NAME}
        app.kubernetes.io/instance: ${POD_NAME}
        app.kubernetes.io/name: ${POD_NAME}
        app.kubernetes.io/part-of: ${POD_NAME}-app
        app.openshift.io/runtime: shadowman
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      internalTrafficPolicy: Cluster
      type: ClusterIP
      selector:
        app: ${POD_NAME}
parameters:
  - name: NAMESPACE
    description: "The project where the application will be deployed."
    required: false
    value: ocp-virt-pgd
  - name: POD_NAME
    description: "The application name."
    required: false
    value: support-tools