---
apiVersion: template.openshift.io/v1
kind: Template
objects:

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: ${STORAGE_CLASS_NAME}
    provisioner: efs.csi.aws.com
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer
    parameters:
      provisioningMode: efs-ap 
      fileSystemId: ${FILE_SYSTEM_ID}
      directoryPerms: "700" 
      gidRangeStart: "1000" 
      gidRangeEnd: "2000" 
      basePath: "/dynamic_provisioning" 
        
parameters:
  - name: STORAGE_CLASS_NAME
    description: "The name of the storage class."
    required: false
    value: efs-csi
  - name: FILE_SYSTEM_ID
    description: "The fileSystemId at AWS EFS."
    required: true
