apiVersion: template.openshift.io/v1
kind: Template
objects:

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${PVC_NAME}
      namespace: ${PVC_NAMESPACE}
    spec:
      accessModes:
        - ${ACCESS_MODE}
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
      storageClassName: ${STORAGE_CLASS_NAME}
        
parameters:
  - name: PVC_NAMESPACE
    description: "The project where the application will be deployed."
    required: false
    value: ocp-virt-pgd
  - name: PVC_NAME
    description: "The PVC name."
    required: false
    value: efs-shared-filesystem
  - name: ACCESS_MODE
    description: "The PVC Access Mode."
    required: false
    value: ReadWriteMany
  - name: STORAGE_CLASS_NAME
    description: "The name of the storage class."
    required: false
    value: efs-csi