---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: shared-disk
objects:
  - apiVersion: cdi.kubevirt.io/v1alpha1
    kind: DataVolume
    metadata:
      name: ${DATAVOLUME_NAME}
      namespace: ${DATAVOLUME_NAMESPACE}
      labels:
        app: ${DATAVOLUME_NAME}
    spec:
      pvc:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 2Gi
        storageClassName: ${STORAGE_CLASS_NAME}
        volumeMode: Filesystem
      source:
        blank: {}
parameters:
  - name: DATAVOLUME_NAMESPACE
    description: "The namespace where the DV will be generated."
    required: false
    value: vms-test
  - name: DATAVOLUME_NAME
    description: "The PVC name."
    required: false
    value: shared-fs
  - name: STORAGE_CLASS_NAME
    description: "The name of the storage class."
    required: false
    value: efs-csi