---
apiVersion: template.openshift.io/v1
kind: Template
metadata: 
  name: metal-worker
objects:
  - apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ${INFRASTRUCTURE_ID}
      name: ${INFRASTRUCTURE_ID}-${PREFIX}${ROLE}-${AZ}
      namespace: openshift-machine-api
    spec:
      replicas: ${{REPLICAS}}
      selector:
        matchLabels:
          machine.openshift.io/cluster-api-cluster: ${INFRASTRUCTURE_ID}
          machine.openshift.io/cluster-api-machineset: ${INFRASTRUCTURE_ID}-${PREFIX}${ROLE}-${AZ}
      template:
        metadata:
          labels:
            machine.openshift.io/cluster-api-cluster: ${INFRASTRUCTURE_ID}
            machine.openshift.io/cluster-api-machine-role: ${ROLE} 
            machine.openshift.io/cluster-api-machine-type: ${ROLE} 
            machine.openshift.io/cluster-api-machineset: ${INFRASTRUCTURE_ID}-${PREFIX}${ROLE}-${AZ}
            usage: virtualization
        spec:
          metadata:
            labels:
              node-role.kubernetes.io/${ROLE}: ""
              usage: virtualization
          providerSpec:
            value:
              ami:
                id: ${AMI}
              apiVersion: machine.openshift.io/v1beta1
              blockDevices:
                - ebs:
                    iops: 0
                    volumeSize: 120
                    volumeType: gp2
              credentialsSecret:
                name: aws-cloud-credentials
              deviceIndex: 0
              iamInstanceProfile:
                id: ${INFRASTRUCTURE_ID}-worker-profile 
              instanceType: ${INSTANCE_TYPE}
              kind: AWSMachineProviderConfig
              placement:
                availabilityZone: ${REGION}${AZ}
                region: ${REGION} 
              securityGroups:
                - filters:
                    - name: tag:Name
                      values:
                        - ${INFRASTRUCTURE_ID}-node 
                - filters:
                    - name: tag:Name
                      values:
                        - ${INFRASTRUCTURE_ID}-lb
              subnet:
                filters:
                  - name: tag:Name
                    values:
                      - ${INFRASTRUCTURE_ID}-subnet-private-${REGION}${AZ}
              tags:
                - name: kubernetes.io/cluster/${INFRASTRUCTURE_ID}
                  value: owned
              userDataSecret:
                name: worker-user-data
parameters:
  - name: REPLICAS
    description: "Number of bare metal nodes."
    required: false
    value: "1"
  - name: ROLE
    description: "Role of the node (Worker or master normally)."
    required: false
    value: worker
  - name: REGION
    description: "Node region."
    required: true
  - name: AZ
    description: "Node zone."
    required: false
    value: a
  - name: PREFIX
    description: "Prefix that will be attached to the node name."
    required: false
    value: metal-
  - name: INSTANCE_TYPE
    description: "EC2 AWS instance type."
    required: false
    value: c5n.metal
  - name: AMI
    description: "AMI of the CoreOS image in that AWS region."
    required: false
  - name: INFRASTRUCTURE_ID
    description: "Cluster ID."
    required: true